### ISSUE TITLE
建议新增的配置项

### ISSUE THREAD

**Issue by zhangzhonghe** [hustcc/G2Plot-QRCode#3]
- [ ] 新增一个配置前景图片的功能
- [ ] 新增一个配置背景图片的功能
- [ ] icon 可以设置位置，可以设置边框、阴影的样式
- [ ] 新增一个可以插入文字的配置项
- [ ] 新增一个可以设置渐变的配置项

**Comment by hustcc** [comment]
3 可做比较简单，其他的我觉得可能比网站工具优先级低吧~
